[versions]
agp = "8.8.0"
android-compileSdk = "34"
android-minSdk = "23"
android-targetSdk = "34"
androidx-activityCompose = "1.9.3"
androidx-lifecycle = "2.8.4"
androidx-navigation ="2.8.0-alpha10"
compose-plugin = "1.7.1"
coreBundle = "1.0.1"
filekitCompose = "0.8.7"
koinAndroidExt = "3.0.2"
kotlin = "2.1.0"
ktor = "3.0.2"
koin = "4.0.0"
kamel="1.0.0-beta.7"
log4jApi = "2.24.3"
kotlin-logging = "7.0.3"
coroutines = "1.9.0"
ksp = "2.1.0-1.0.29"
logging = "1.5.0"
mp_stools = "1.5.1"
multiplatformSettingsNoArg = "1.2.0"
slf4jSimple = "2.0.16"
sqlite = "2.5.0-SNAPSHOT"
androidx-room = "2.7.0-alpha09"
testng = "7.4.0"
uiUtil = "1.7.1"


[libraries]
core-bundle = { module = "org.jetbrains.androidx.core:core-bundle", version.ref = "coreBundle" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-ext = { module = "io.insert-koin:koin-android-ext", version.ref = "koinAndroidExt" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-json-jvm = { module = "io.ktor:ktor-client-json-jvm", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-cio= {module ="io.ktor:ktor-client-cio", version.ref = "ktor"}
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
kotlin-serialization = {module = "io.ktor:ktor-serialization-kotlinx-json", version.ref="ktor"}
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4jApi" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4jApi" }
org-apache-logging-log4j-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4jApi" }
logging = { module = "org.lighthousegames:logging", version.ref = "logging" }
media-kamel = {module="media.kamel:kamel-image", version.ref="kamel"}
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref= "ktor"}
ktor-network = {module = "io.ktor:ktor-network", version.ref= "ktor"}
ktor-utils = {module = "io.ktor:ktor-utils", version.ref= "ktor"}
koin-compose = {module="io.insert-koin:koin-compose", version.ref = "koin"}
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
mp_stools = { module = "net.sergeych:mp_stools", version.ref = "mp_stools" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettingsNoArg" }
navigation-common = { module = "org.jetbrains.androidx.navigation:navigation-common", version.ref = "androidx-navigation" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "uiUtil" }

[bundles]
ktor = ["ktor-client-core", "ktor-client-content-negotiation"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}